### ISSUE TITLE
The java rpm is an empty file

### ISSUE THREAD

**Issue by davecb** [eucuepo/vagrant-kafka#13]
I installed vagrant-kafka, but it logged
```
    broker3: installing JDK and Kafka...
    broker3: error: 
    broker3: not an rpm package
    broker3: error: 
    broker3: /vagrant/rpm/jdk-8u151-linux-x64.rpm: not an rpm package (or package manifest): 
```
None of the vms had java, so I got
```
$ vagrant ssh zookeeper1
[vagrant@zookeeper1 ~]$ /vagrant/scripts/create-topic.sh test-one
/home/vagrant/kafka_2.11-1.0.0/bin/kafka-run-class.sh: line 270: exec: java: not found
```

**Comment by davecb** [comment]
I'll look for an rpm of that java and report if installing it returns me to normal.

**Comment by davecb** [comment]
I downloaded jdk-8u161-linux-x64.rpm from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
mv'd it to rmp/jdk-8u151-linux-x64.rpm and ran vagrant up --provision 

The one-line and vmstat tests both worked, so a sufficient workaround is to use a somewhat newer jave.

**Comment by imarios** [comment]
Thank you very much for your feedback and workaround.

 
keeping the links “fresh” is a problem. Links may work for few months and then taken down and replaced. I have yet to find a way to have these links stand the test of time. In fact, I updated everything few months against and since then things have change..

**Comment by imarios** [comment]
The URL you have works, but it requires a manual acceptance of Oracles license agreement. I think the best solution is to move to openjdk.

**Comment by imarios** [comment]
Hi @davecb, again thanks for your feedback. 

If you have the time, I have update the example on github using centos 6.9 and streamlining the way java was installed. 

I think this iteration makes java installation much more robust. Can you please give it a try and let me know if things work ok for you? Note that now the recommendation is to use the latest version of vagrant (which is 2.0.2 as of this moment).
