### ISSUE TITLE
Oracle lincense not accepted when downloading JDK

### ISSUE THREAD

**Issue by cleankod** [eucuepo/vagrant-kafka#2]
The license need to be accepted in order to download the JDK from Oracle.

To make that happen, just add this cookie to wget:
`Cookie: oraclelicense=accept-securebackup-cookie`

Resulting in:

```
wget -O /vagrant/rpm/jdk-7u45-linux-x64.rpm --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/7u45-b18/jdk-7u45-linux-x64.rpm"
```

**Comment by justizin** [comment]
It might be a license violation to distribute a script that does this, fwiw.

I'm exploring whether kafka and zk work OK against openjdk.  The Oracle package doesn't satisfy the 'java' requirement properly.

**Comment by imarios** [comment]
I think this can be marked as closed as now the latest version works.

**Comment by eucuepo** [comment]
Fixed by @imarios PR https://github.com/eucuepo/vagrant-kafka/pull/3
