### ISSUE TITLE
Can't run scripts to create or list topics

### ISSUE THREAD

**Issue by caddac** [eucuepo/vagrant-kafka#5]
I've succesfully ssh'd into one of the brokers, but when trying to run the script (or any of the scripts) `/vagrant/scripts/create_topic.sh` I get the error `-bash: /vagrant/scripts/create_topic.sh: /bin/bash^M: bad interpreter: No such file or directory`

I'm running this on Windows 10 in Powershell, but I've also tried in Cmd. Looks like a line ending issue?

**Comment by caddac** [comment]
I ran `sed -i -e 's/\r$//' /vagrant/scripts/create_topic.sh` and it fixed the issue.

[bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory](http://stackoverflow.com/a/29747593/2336736)

**Comment by imarios** [comment]
@caddac, it does sound like Windows vs Linux line feed difference. Glad you figured out a solution to this. Be careful when you edit files in Windows and then run them on Linux, and vice versa.

**Comment by caddac** [comment]
@imarios I didn't edit them beyond running the sed command to fix the issue. Seems like vagrant-kafka targets a linux host? I guess when I cloned the repo initially I changed the line endings in the files.

**Comment by imarios** [comment]
@caddac I only tried this on a Mac. You are right, the way we test it right now, it might not be fully windows compatible.
